### ISSUE TITLE
Plans to implement more ciphers in OpenSSH

### ISSUE THREAD

**Issue by Leo1003** [RustCrypto/SSH#108]
Hello, I am the author of another similar crate [osshkeys](https://github.com/Leo1003/rust-osshkeys). And I am interested in participate in this project.

Since there are more ciphers implemented in [openssh/openssh-portable/cipher.c](https://github.com/openssh/openssh-portable/blob/master/cipher.c) still missing in this library:

- AES-128-CBC
- AES-192-CBC
- AES-256-CBC
- AES-128-CTR
- AES-192-CTR
- AES-128-GCM
- TDES-CBC
- chacha20-poly1305

I want to ask if there is any plan to support all these ciphers. If true, I think I am able to help working on this.

**Comment by tarcieri** [comment]
Hi, thanks for opening the issue!

Filling these out seems good, although I'd prioritize everything else over triple DES.
