### ISSUE TITLE
`ssh_key::certificate::Builder::new_with_validity_times` incorrectly names validity time arguments

### ISSUE THREAD

**Issue by pjht** [RustCrypto/SSH#142]
As described in the title, new_with_validity_time has the validity time arguments the wrong way around. What is listed as valid_after is really valid_before, and valid_before is really valid_after. This seems to be due to a swap when it calls Builder::new, passing valid_after as valid_before and vice versa.

**Comment by tarcieri** [comment]
Indeed they are swapped.

Looks like this method has no tests. Adding some should likely cause it to fail until they're swapped into the correct order.

**Comment by tarcieri** [comment]
Opened #143
