### ISSUE TITLE
`ssh-key` 0.6.0 release

### ISSUE THREAD

**Issue by gabi-250** [RustCrypto/SSH#150]
Hi!

Are there any plans to cut a new `ssh-key` release soon?

**Comment by tarcieri** [comment]
Yes, should be later today. I've already cut releases of the prerequisites (`ssh-cipher` and `ssh-encoding`)

**Comment by tarcieri** [comment]
Released in #151

**Comment by gabi-250** [comment]
That was quick -- thank you!
