### ISSUE TITLE
`ssh-cipher`: Cipher::{encrypt, decrypt} does not persist cipher state.

### ISSUE THREAD

**Issue by lowlevl** [RustCrypto/SSH#164]
Hi there, first of all thanks for the work on those 3 crates, they're really coming handy when implementing SSH primitives !

About the interfaces for `ssh-cipher`, it seems like calling `Cipher::encrypt` or `Cipher::decrypt` at different times to encrypt/decrypt SSH packet doesn't preserve the inner state of the Cipher and produce invalid data.
I may be doing something wrong however, but so far I am only able to decrypt and encrypt the first packet after the key-exchange, the successive packets gets mangled.
I test my code against OpenSSH, so I'd guess the client is behaving correctly in this case.

**Comment by tarcieri** [comment]
The `ssh-cipher` API is an extraction from `ssh-key` and largely designed around the concerns of encrypting SSH private key files, so it's possible that its API is somewhat unhelpful for an SSH protocol implementation.

However, it's designed to support AEAD modes which by definition have a one-shot API and can't support incremental decryption at the very least.

I would be curious to know more about the applications for stateful/incremental decryption/encryption and what happens in those cases when an AEAD mode is used instead.

**Comment by tarcieri** [comment]
We can support it, yes, though I would suggest implementing the AEAD modes first before deciding on an abstraction.

**Comment by tarcieri** [comment]
Nice, that looks quite promising!

So, would it be helpful to have a stateful `Cipher` object which could be reused for the legacy modes, but is only one-shot for the AEAD modes?

That would be a breaking change but something we could potentially accommodate in the next release.

**Comment by tarcieri** [comment]
Yeah, it would probably involve `Cipher` creating stateful `Encryptor`/`Decryptor` objects which are themselves enums over the various possible modes
