### ISSUE TITLE
Is it possible to use this crate to verify SSH signed files?

### ISSUE THREAD

**Issue by wiktor-k** [RustCrypto/SSH#165]
Hi,

Sorry if this is a wrong place to ask but I was wondering if it's possible to use this crate to verify SSH signed files? (Basically what `ssh-keygen -Y verify` does, more details at https://www.agwa.name/blog/post/ssh_signatures).

SSH file signatures are becoming quite widespread since they are used for git SSH signatures (an alternative to OpenPGP signatures, see https://calebhearth.com/sign-git-with-ssh).

Thanks for your time! 👋

**Comment by tarcieri** [comment]
Yes, see https://docs.rs/ssh-key/latest/ssh_key/struct.SshSig.html

**Comment by tarcieri** [comment]
#166 adds a signature verification example

**Comment by wiktor-k** [comment]
Thank you! 🙏
