### ISSUE TITLE
possible curve and field size mismatches in Signature conversions?

### ISSUE THREAD

**Issue by jclulow** [RustCrypto/SSH#197]
Are these quite right?

https://github.com/RustCrypto/SSH/blob/8abfc945c0c20a2aa4171581df06f1835a226725/ssh-key/src/signature.rs#L554-L563

https://github.com/RustCrypto/SSH/blob/8abfc945c0c20a2aa4171581df06f1835a226725/ssh-key/src/signature.rs#L584-L593

Critically, we seem to be matching on **EcdsaCurve::NistP256** in the **p384** and **p521** cases here...

Also the **FIELD_SIZE** constant is the same for **p384** and **p521**?

**Comment by tarcieri** [comment]
Indeed that does look bogus / like a copy paste error.

It seems these likely don't have tests, which would also be good to add in addition to fixing them.
