### ISSUE TITLE
Missing constructors for `SkEd25519`

### ISSUE THREAD

**Issue by jviki** [RustCrypto/SSH#200]
I've got sk-ed25519 public key bytes, sk application string, sk flags byte and would like to construct the PrivateKey and write it out in the OpenSSH format. I didn't find out how to do it. It seems like there are missing any constructors or means for constructing the data structs, especially KeypairData and KeyData. Do I miss something or is it currently not possible?

**Comment by tarcieri** [comment]
Added in #201
