### ISSUE TITLE
Busted advisories link

### ISSUE THREAD

**Issue by jcape** [RustCrypto/SSH#203]
Hey, just a heads up that the advisory reporting link at https://github.com/RustCrypto/SSH/blob/8c6e81c748762011703bd4294db792e7811d8bba/SECURITY.md?plain=1#L14 is broken (I don't have anything to report, just noticed the issue.

**Comment by tarcieri** [comment]
What is it doing for you? It works for me.

**Comment by jcape** [comment]
![image](https://github.com/RustCrypto/SSH/assets/35878/b16a8286-9199-448b-a6ee-887562ecd62f)

**Comment by tarcieri** [comment]
Try again? I just enabled private vulnerability reporting

**Comment by jcape** [comment]
Yep, works now
