### ISSUE TITLE
Using `KeypairData` with secrecy

### ISSUE THREAD

**Issue by wiktor-k** [RustCrypto/SSH#228]
Hi,

I've begun exploring using secrecy for [handling secrets in the ssh-agent-lib](https://github.com/wiktor-k/ssh-agent-lib/pull/63) and wanted to wrap the [`KeypairData`](https://github.com/RustCrypto/SSH/blob/f8454bc2f26d902551b89195c6a876b432a9d1cd/ssh-key/src/private/keypair.rs#L27) (which contains private key material) but it seems secrecy requires the wrapped type to implement `Zeroize`.

It seems the crate already [uses `zeroize`](https://github.com/RustCrypto/SSH/blob/master/ssh-key/Cargo.toml#L25) but it's not clear to me if **not** implementing `Zeroize` trait for `KeypairData` is by design or not.

I'm happy to contribute a fix if this looks like a good idea.

**Comment by tarcieri** [comment]
`KeypairData` is already designed to clear its own secrets on drop and avoid leaking them in `Debug` impls.

`secrecy` is designed for working with types which were not designed that way from the get go.

Adding `Zeroize` impl to a type like a private key risks a use-after-zeroize condition where the key has been zeroed but is still used for cryptography, which is insecure. It’s deliberate whenever a type impls `ZeroizeOnDrop` but not `Zeroize`.

**Comment by wiktor-k** [comment]
Thanks for the detailed explainer!
