### ISSUE TITLE
Why does new `Signature` keep getting the error "invalid length" when `Algorithm` is ssh-rsa?

### ISSUE THREAD

**Issue by ycysdf** [RustCrypto/SSH#262]
![image](https://github.com/user-attachments/assets/9d4567cc-70d8-4b4f-9619-c50593d25afb)

**Comment by tarcieri** [comment]
Based on that `match`, my best guess is you're giving it `Algorithm::Rsa { hash: None }`. Can you confirm?

If so, `Error::Length` probably isn't the best error to be giving for that case.

**Comment by tarcieri** [comment]
That currently appears to be unsupported. Offhand I'm not sure what the reason was, but I would agree `Error::Length` is definitely not the right error. It could perhaps be supported, I'd have to check the signature specs again.

**Comment by tarcieri** [comment]
It looks like it should be allowed under RFC4253 Section 6.6: https://datatracker.ietf.org/doc/html/rfc4253#section-6.6

Currently it looks like only RFC8332 signatures are supported: https://datatracker.ietf.org/doc/html/rfc8332

**Comment by tarcieri** [comment]
@ycysdf can you post the signature you're trying to parse?
