### ISSUE TITLE
Backporting `ssh-key` bug fixes to 0.6.x

### ISSUE THREAD

**Issue by mkeeter** [RustCrypto/SSH#296]
I've backported #289 and #291 to `ssh-key/v0.6.6`, and updated the CHANGELOG:

https://github.com/oxidecomputer/SSH/commits/ssh-key/v0.6.6-backports/

It would be great to have this released as 0.6.7, so that we don't have to use a `git` dependency while waiting for the 0.7.0 release.  In particular, #291 is causing our CI runs to occasionally fail, since picking an undersized `mpint` is a matter of bad luck.

Thanks!

**Comment by steveklabnik** [comment]
Hey @tarcieri, any chance you have a moment to take a look at this?

**Comment by tarcieri** [comment]
@mkeeter can you open a PR and target the `stable` branch?

**Comment by tarcieri** [comment]
Released in v0.6.7 (#302)
