### ISSUE TITLE
`Algorithm::new_certificate` incorrectly parses `rsa-sha2-*` certificate algos

### ISSUE THREAD

**Issue by Eugeny** [RustCrypto/SSH#310]
Currently [Algorithm::new_certificate](https://github.com/RustCrypto/SSH/blob/52ed3e06cd7b8ca7c6c9afc45558d2c7c5c11309/ssh-key/src/algorithm.rs#L165) parses `rsa-sha2-*-cert-v01@openssh.com` algos as `Algorithm::Other` instead of `Algorithm::Rsa { hash: Some(...) }`

**Comment by tarcieri** [comment]
Fixed in #311
