### ISSUE TITLE
`Signature::new` for SK/FIDO is on a weird abstraction level

### ISSUE THREAD

**Issue by Eugeny** [RustCrypto/SSH#312]
Currently, `Signature::new` actually takes a half-decoded auth packet as its input. Consider the following:

USERAUTH_REQUEST packet for ECDSA SK is:

```
	string		"sk-ecdsa-sha2-nistp256@openssh.com"
           u32 <len>
           ... <chars>
	string		ecdsa_signature
           u32 <len>
           ... <chars>
	byte		flags
	uint32		counter
```

the `data` argument for `Signature::new` actually expects the following data chunk, which begins _inside_ a string value

```
  	string		"sk-ecdsa-sha2-nistp256@openssh.com"
             u32 <len>
             ... <chars>
  	string		ecdsa_signature
             u32 <len>
->           ... <chars>
| 	byte		flags
| 	uint32		counter
->
```

(this is due to the fact that for SK keys, `Signature` needs the `flags` and `counter` fields, see `SK_SIGNATURE_TRAILER_SIZE`)

This means that the library consumer would usually first decode the packet into an `mpstring` + `byte` + `u32`, and then have to reconstruct the buffer that `Signature` expects, or wonkily use `&original_buffer[4:]`

I don't have concrete suggestions except maybe passing a `Reader` to `Signature::new`, letting it decode any additional values based on the `algorithm` value

**Comment by tarcieri** [comment]
> I don't have concrete suggestions except maybe passing a Reader to Signature::new, letting it decode any additional values based on the algorithm value

Elsewhere we call that `decode_as`, e.g. [`Certificate::decode_as`](https://docs.rs/ssh-key/0.7.0-pre.1/ssh_key/certificate/struct.Certificate.html#method.decode_as).

That would allow you to [leverage the logic in the `Decode` impl for handling this case](https://github.com/RustCrypto/SSH/blob/f28658e/ssh-key/src/signature.rs#L181-L187).

**Comment by Eugeny** [comment]
Perfect, thanks!
