### ISSUE TITLE
ssh key generation takes very long sometimes

### ISSUE THREAD

**Issue by xemwebe** [RustCrypto/SSH#56]
I use the following code to generate a ssh key pair:
```
RsaKeypair::random(rand::thread_rng(), 2048)
```
which takes usually a few seconds (e.g 2-5s cpu time), but sometimes much longer, e.g. up to 20s and more.
Since the time taken varies a lot, I suspect this might be due to lack of entropy, especially since the required time seems to be much longer in un-attended scenarios (e.g. automatic testing). 

Is this a known (accepted?) phenomenon? Could the long duration be circumvented somehow, especially in automatic testing scenarios?

**Comment by xemwebe** [comment]
Yes indeed, the long times are only observed in debug builds? I was just observing this in my own tests. 
For some reasons, I need RSA based key for compatibility, but since using `--release` fixes the issue, this issue could be closed, I guess.

Thanks for the fast help!

**Comment by tarcieri** [comment]
In your workspace's Cargo.toml, you can also add something like:

```
[profile.dev]
opt-level = 2
```

...which will improve the speed at which tests run.
