### ISSUE TITLE
How to use ssh-key in a no-std environment?

### ISSUE THREAD

**Issue by mbs0221** [RustCrypto/SSH#57]
Hello, everyone! Here comes a problem!

When I introduce the `ssh-key` crate to a `no-std` environment with following line in `Cargo.toml`.
```
ssh-key = { version = "0.5.1", default-features = false }
```

The build process failed with an error as following, even if I didn't use this crate in the project.

```
LLVM ERROR: Do not know how to split the result of this operator!

error: could not compile `sha2`
warning: build failed, waiting for other jobs to finish...
```

So how to use `ssh-key` in a `no-std` environment? Any help would be appreciated!

**Comment by tarcieri** [comment]
Seems like you're running into this issue: https://github.com/RustCrypto/hashes/issues/446

**Comment by tarcieri** [comment]
@mbs0221 as a workaround, you can try adding `sha2` to your Cargo.toml and enabling the `force-soft` feature

**Comment by mbs0221** [comment]
> @mbs0221 as a workaround, you can try adding `sha2` to your Cargo.toml and enabling the `force-soft` feature

Many thanks for your timely help. It solved my problem!

**Comment by tarcieri** [comment]
@mbs0221 can you tell me the target triple where this problem is occurring? Is it `x86_64-unknown-uefi` or something else?

**Comment by tarcieri** [comment]
Closing in favor of https://github.com/RustCrypto/hashes/issues/446

**Comment by mbs0221** [comment]
> @mbs0221 can you tell me the target triple where this problem is occurring? Is it `x86_64-unknown-uefi` or something else?

I use `ssh-key` in a no-std environment. The target triple is `x86_64-unknown-none`, not `x86_64-unknown-uefi`.
